import type { Metadata } from "next";
import { Geist, Geist_Mono, Comforter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * ${geistMono.variable} - 应用 Geist Mono 字体的 CSS 变量。
 * 这个变量名是 --font-geist-mono，同样可以在应用中通过 CSS 变量引用。
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/**
 * 配置字体
 * ${inter.className} - 应用 Comforter 字体的类名。
 * 注意这里使用的是 className 而不是 variable，这是因为 Comforter 字体是直接通过类名应用的，而不是通过 CSS 变量。
 */
const inter = Comforter({
  subsets: ["latin"],
  weight: "400",
});

/**
 * 根layout
 * @param param0
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
